---
title: "Conteo rapido muestra estratificada proporcional"
author: "Equipo 1"
date: "2/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(readxl)
library(dplyr)
library(janitor)
library(kableExtra)
library(tidyverse)
library(extrafont)
library(scales)
library(showtext)
library(tint)
library(miniUI)
library(units)
library(ggfortify)
library(cowplot)
library(magrittr)
library(Cairo)
```

```{r}
rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)
source("funciones/muestra.R")
#source("funciones/calculaECM.R")
#source("funciones/funcionesSimulacion.R")
source("funciones/funcionSimulaEstrVar-02.R")
```


## Lectura de datos

```{r}
gobernador2015<- read_excel("data/ComputoGobernador2015_Casilla.xlsx", 
                            sheet = "POR CASILLA", skip = 1) %>%
  clean_names()
UbicacionCasillas2015 <- read_excel("data/UbicacionCasillas2015.xlsx", skip = 4) %>%
  clean_names()
casillas_sonora <- read.csv("data/casillas_sonora.csv")  %>%
  select(seccion, casilla_tipo) %>%
  distinct(seccion, casilla_tipo) %>%
  rbind(c(608, "RURAL"))
casillas_sonora$seccion %<>% as.numeric()

gobernador2015 %>%
  head()
```

Se agrega lista nominal a la tabla de resultados por casilla

```{r}
gobernador2015 <- UbicacionCasillas2015 %>%
  left_join(gobernador2015, ., by = c("seccion", "casilla")) %>%
  select(-c(distrito_local.y, municipio.y, domicilio)) %>%
  mutate(seccion_casilla = paste(seccion, casilla)) %>%
  rename(municipio = municipio.x,
         distrito_local = distrito_local.x)
  
gobernador2015 <- casillas_sonora %>%
  left_join(gobernador2015, ., by = "seccion") %>%
  mutate(distrito_tipo = paste(distrito_local,casilla_tipo))
rm(casillas_sonora)

gobernador2015 %>%
  head()
```

## Resultado real

```{r}
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) -> resultadoReal
resultadoReal
```

Tamaño de muestra y número de repeticiones

```{r}
N <- length(gobernador2015$seccion_casilla)  # total de casillas
n <- muestra(N)                              # Número de secciones en la muestra
M <- 3                                   # Número de repeticiones
```

## Resumen por distrito

```{r, message = FALSE}
df.distritos <- gobernador2015 %>%
  group_by(distrito_local) %>%
  summarise(LN = sum(lista_nominal),
            Nh = n(),           # Casillas por distrito
            #p = Nh / N) %>%
            p = LN/sum(gobernador2015$lista_nominal)) %>%   # Proporción
  mutate(nh = round(num.casillas = n * p)) %>%
  arrange(distrito_local)
df.distritos
```

```{r, message = FALSE}
distritos <- df.distritos$distrito_local
  nh <- df.distritos$nh
  Nh <- df.distritos$Nh
  L <- length(distritos)

  resultado <- data.frame()
  df<-gobernador2015 # ELIMINAR
  i <- 1 # ELIMINAR

  estPRI <-rep(0, M)
  estPAN <-rep(0, M)
  varPRI <-rep(0, M)
  varPAN <-rep(0, M)
  estTotal <-rep(0, M)

  for(i in 1:M){
    muestra <- c() 
    # Selecciona la muestra dentro de cada estrato
    for(j in 1: L){
      df %>%
        filter(distrito_local == distritos[j]) %>%
        select(seccion_casilla) -> df.muestra
      muestra <- c(muestra, sample(df.muestra$seccion_casilla, df.distritos$nh[j]))
    }
    
    # Se calcula el porcentaje de votos de cada estrato para cada muestra
    df.temporal <- df %>%
      filter(seccion_casilla %in% muestra) %>%
      group_by(distrito_local) %>% 
      summarise(PRI = sum(total_coalicion), #suma sobre las casillas: 1 hasta nh
                PAN = sum(pan),   # sum (Yhi)
                Total = sum(votacion_total_emitida)) # Xh
                #Wh = Nh / nh)
    df.temporal <- cbind(df.temporal, Wh = Nh / nh)
    
    estTotal[i] = df.temporal$Wh %*% df.temporal$Total #X gorro
    estPAN[i] = df.temporal$Wh %*% df.temporal$PAN / estTotal[i]
    estPRI[i] = df.temporal$Wh %*% df.temporal$PRI / estTotal[i]

    df2 <- df %>%
      filter(seccion_casilla %in% muestra) %>%
      select(distrito_local, seccion_casilla, 
             total_coalicion, pan, votacion_total_emitida) %>%
      mutate(GhiPAN = (pan - estPAN[i]*votacion_total_emitida) / estTotal[i])
  
    df2 %>%
      group_by(distrito_local) %>%
      summarise(Gh.barraPAN = mean(GhiPAN)) -> Gh.barraPAN
    
    df2 <- df2 %>%
      left_join(Gh.barraPAN) %>%
      mutate(Ghi_GhPAN = (GhiPAN - Gh.barraPAN)^2)
  
    df2 %>%
      group_by(distrito_local) %>%
      summarise(numeradorPAN = sum(Ghi_GhPAN)) %>%
      mutate(denominadorPAN = nh - 1,
             VarGhiPAN = numeradorPAN / denominadorPAN) %>%
      select(VarGhiPAN) -> VarGhiPAN
  
    varPAN[i] <- sum(Nh^2 * (1/nh - 1/Nh) * VarGhiPAN)

    ## INICIA PRI
    df3 <- df %>%
      filter(seccion_casilla %in% muestra) %>%
      select(distrito_local, seccion_casilla, 
             total_coalicion, pan, votacion_total_emitida) %>%
      mutate(GhiPRI = 
               (total_coalicion - estPRI[i]*votacion_total_emitida) / estTotal[i])
  
    df3 %>%
      group_by(distrito_local) %>%
      summarise(Gh.barraPRI = mean(GhiPRI)) -> Gh.barraPRI
    
    df3 <- df3 %>%
      left_join(Gh.barraPRI) %>%
      mutate(Ghi_GhPRI = (GhiPRI - Gh.barraPRI)^2)
  
    df3 %>%
      group_by(distrito_local) %>%
      summarise(numeradorPRI = sum(Ghi_GhPRI)) %>%
      mutate(denominadorPRI = nh - 1,
             VarGhiPRI = numeradorPRI / denominadorPRI) %>%
      select(VarGhiPRI) -> VarGhiPRI
  
    varPRI[i] <- sum(Nh^2 * (1/nh - 1/Nh) * VarGhiPRI)
  }    
  
  deltaPAN <- sqrt(varPAN) * 2.575
  deltaPRI <- sqrt(varPRI) * 2.575
  
  resultado <- cbind(estPRI, estPAN, varPRI, varPAN, deltaPAN, deltaPRI)
  colnames(resultado) <- c("estPRI", "estPAN", 
                           "varPRI", "varPAN", "deltaPAN", "deltaPRI")
  resultado <- resultado %>%
    as.data.frame() %>%
    mutate(dif.PRI = estPRI - resultadoReal$PRI,
           dif.PAN = estPAN - resultadoReal$PAN)
```

```{r}
simulacionESTR01 <- resultado

simulacionESTR01 <- simulacionESTR01 %>%
  mutate(MinPRI = estPRI - (2.575 * sqrt(varPRI)),
         MaxPRI = estPRI + (2.575 * sqrt(varPRI)),
         MinPAN = estPAN - (2.575 * sqrt(varPAN)),
         MaxPAN = estPAN + (2.575 * sqrt(varPAN)),
         capturaPRI = resultadoReal$PRI > MinPRI & resultadoReal$PRI < MaxPRI,
         capturaPAN = resultadoReal$PAN > MinPAN & resultadoReal$PAN < MaxPAN,
         no.Traslape = MaxPAN < MinPRI,
         longIntPRI = MaxPRI-MinPRI,
         longIntPAN = MaxPAN-MinPAN)
captura_verdad <- data.frame()
captura_verdad <- captura_verdad %>%
  rbind(simulacionESTR01 %>%
          select(capturaPRI, capturaPAN, no.Traslape) %>%
          summarise(PRI.capturado = 100*length(capturaPRI[capturaPRI==TRUE]) / M,
                    PAN.capturado = 100*length(capturaPAN[capturaPAN==TRUE]) / M,
                    no.Traslapado = 100*length(no.Traslape[no.Traslape==TRUE])/M))
captura_verdad

simulacionESTR01 %>%
  select(MinPAN, estPAN, MaxPAN, varPAN, deltaPAN, capturaPAN) %>%
  head()

simulacionESTR01 %>%
  select(MinPRI, estPRI, MaxPRI, varPRI, deltaPRI, capturaPRI) %>%
  head()

hist(simulacionESTR01$estPAN)
hist(simulacionESTR01$estPRI)
```

```{r, echo=FALSE}
Tema <- theme(plot.title = (element_text(size = 20, color = "black")),
              plot.subtitle = (element_text(size = 10, color = "black")),
              legend.position = "top",  plot.margin = margin(0.5, 1, 0.5, 1, "cm"),
              legend.key.height = unit (0.2, "cm"), legend.key.width = unit (0.2, "cm"),
              axis.text = element_text(size = 10, color = "black"),
              legend.text = element_text(size = 8, color = "black"),
              legend.title = element_text(size = 10, color = "black"),
              plot.caption = element_text(size = 10, color = "black", face="italic"),
              axis.title = element_text(size = 12, color = "black"))
```

## Error: Estratificado (proporcional)

```{r}
df.simulacion <- simulacionESTR01
variable <- simulacionESTR01$dif.PRI
error <- ggplot(data=df.simulacion, aes(x=variable^2)) +
  geom_histogram(bins=50, color="red", fill = "red", alpha=0.5)+
  scale_y_continuous(labels = comma) +
  theme_bw() + Tema +
  labs(fill = "Partido", color= NULL, 
       x = "Diferencia al cuadrado", 
       y = "Observaciones", 
       title = NULL,
       caption = NULL, 
       subtitle = paste("Errores de", M, 
                        "simulaciones respecto al resultado observado"))
show(error)
```

```{r}
df.simulacion <- simulacionESTR01
variable <- simulacionESTR01$dif.PAN
error <- ggplot(data=df.simulacion, aes(x=variable^2)) +
  geom_histogram(bins=50, color="blue", fill = "blue", alpha=0.5)+
  scale_y_continuous(labels = comma) +
  theme_bw() + Tema +
  labs(fill = "Partido", color= NULL, 
       x = "Diferencia al cuadrado", 
       y = "Observaciones", 
       title = NULL,
       caption = NULL, 
       subtitle = paste("Errores de", M, 
                        "simulaciones respecto al resultado observado"))
show(error)
```


```{r}
graficaHistograma <-function(df.simulacion, vtitulo){
  M <- length(df.simulacion[,1])
  
  comp <- ggplot(data=df.simulacion) +
    geom_histogram(aes(x=estPRI, fill="PRI"),color="red",  alpha=0.5)+
    geom_histogram(aes(x=estPAN, fill="PAN"), color="blue",  alpha=0.5)+
    scale_fill_manual(breaks = c("PRI", "PAN"),
                      values=c("red", "blue")) +
    theme_bw() + Tema +
    labs(fill = "Partido", color= NULL, y = "", x = "% votación", title = vtitulo,
         caption = NULL, subtitle = paste("Resultados de",M, "simulaciones"))
  show(comp)
}
```

```{r}
simulacionESTR01 %>%
  graficaHistograma("Simulación: Muestreo estratificado proporcional")
```
