---
title: "Conteo rapido muestra estratificada proporcional"
author: "Equipo 1"
date: "2/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
#, echo = FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(readxl)
library(dplyr)
library(janitor)
library(kableExtra)
library(tidyverse)
library(extrafont)
library(scales)
library(showtext)
library(tint)
library(miniUI)
library(units)
library(ggfortify)
library(cowplot)
library(magrittr)
library("Cairo")
rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)
source("funciones/muestra.R")
source("funciones/calculaECM.R")
#source("funciones/graficaHistograma.R")
#source("funciones/graficaError.R")
source("funciones/funcionesSimulacion.R")
source("funciones/funcionSimulaEstrVar.R")
```

## Lectura de datos

```{r}
gobernador2015<- read_excel("data/ComputoGobernador2015_Casilla.xlsx", 
                            sheet = "POR CASILLA", skip = 1) %>%
  clean_names()
UbicacionCasillas2015 <- read_excel("data/UbicacionCasillas2015.xlsx", skip = 4) %>%
  clean_names()
casillas_sonora <- read.csv("data/casillas_sonora.csv")  %>%
  select(seccion, casilla_tipo) %>%
  distinct(seccion, casilla_tipo) %>%
  rbind(c(608, "RURAL"))
casillas_sonora$seccion %<>% as.numeric()
```

Se agrega lista nominal a la tabla de resultados por casilla

```{r}
gobernador2015 <- UbicacionCasillas2015 %>%
  left_join(gobernador2015, ., by = c("seccion", "casilla")) %>%
  select(-c(distrito_local.y, municipio.y, domicilio)) %>%
  mutate(seccion_casilla = paste(seccion, casilla)) %>%
  rename(municipio = municipio.x,
         distrito_local = distrito_local.x)
  
gobernador2015 <- casillas_sonora %>%
  left_join(gobernador2015, ., by = "seccion") %>%
  mutate(distrito_tipo = paste(distrito_local,casilla_tipo))
rm(casillas_sonora)
```

## Resultado real

```{r}
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) -> resultadoReal
resultadoReal
```

Tamaño de muestra y número de repeticiones

```{r}
N <- length(gobernador2015$seccion_casilla)  # total de casillas
n <- muestra(N)                              # Número de secciones en la muestra
M <- 10                                    # Número de repeticiones
```


## Simulación

```{r, message = FALSE}
df.distritos <- gobernador2015 %>%
  group_by(distrito_local) %>%
  summarise(LN = sum(lista_nominal),
            N.dist = n(),           # Casillas por distrito
            p = LN/sum(gobernador2015$lista_nominal)) %>%   # Proporción
  mutate(n.dist = round(num.casillas = n * p)) %>%
  arrange(distrito_local)
df.distritos
```

```{r}
distritos <- df.distritos$distrito_local
  N.dist <- df.distritos$N.dist
  n.dist <- df.distritos$n.dist
  L <- length(distritos)
  N <-sum(N.dist)
  
  # Crea una matriz vacía para el resultado
  resultado <- data.frame()
  df<-gobernador2015
  # aquí se guardarán el estimador y varianza de cada partido, de cada muestra
  estPRI <-rep(0, M)
  estPAN <-rep(0, M)
  Gh <-rep(0, M)
  varPRI <-rep(0, M)
  varPAN <-rep(0, M)
  estTotal <-rep(0, M)
  i<-1
  for(i in 1:M){
    muestra <- c() 
    # en este ciclo se selecciona la muestra dentro de cada estrato
    for(j in 1: L){
      df %>%
        filter(distrito_local == distritos[j]) %>%
        select(seccion_casilla) -> df.muestra
      muestra <- c(muestra, sample(df.muestra$seccion_casilla, df.distritos$n.dist[j]))
    } 
    
    # Se calcula el porcentaje de votos de cada estrato para cada muestra
    
    df.temporal <- df %>%
      filter(seccion_casilla %in% muestra) %>%
      group_by(distrito_local) %>% 
      summarise(PRI = sum(total_coalicion), #suma sobre las casillas: 1 hasta nh
                PAN = sum(pan),
                Total = sum(total_votos_validos),
                Wh = N.dist / n.dist)

    estTotal[i] = df.temporal$Wh %*% df.temporal$Total
    estPRI[i] = df.temporal$Wh %*% df.temporal$PRI / estTotal[i]
    estPAN[i] = df.temporal$Wh %*% df.temporal$PAN / estTotal[i]
    
    df2 <- df %>%
      filter(seccion_casilla %in% muestra) %>%
      select(distrito_local, seccion_casilla, total_coalicion, pan, total_votos_validos) %>%
      mutate(Ghi = (pan - estPAN[i]*total_votos_validos)/estTotal[i])
    
    df2 %>%
      group_by(distrito_local) %>%
      summarise(Gh.barra = mean(Ghi)) -> Gh.barra
    
    df2 <- df2 %>%
      left_join(Gh.barra) %>%
      mutate(Ghi_Gh = (Ghi - Gh.barra)^2)
    
    df2 %>%
      group_by(distrito_local) %>%
      summarise(numerador = sum(Ghi_Gh)) %>%
      mutate(denominador = n.dist - 1,
             VarGhi = numerador / denominador) %>%
      select(VarGhi) -> VarGhi
      
    varPAN <- sum(N.dist^2 * (1/n.dist - 1/N.dist) * VarGhi)
    
    delta <- sqrt(varPAN) * 2.575
    }
  
  resultado <- cbind(estPRI, estPAN, varPRI, varPAN)
  colnames(resultado) <- c("estPRI", "estPAN", "varPRI", "varPAN")
  resultado <- resultado %>%
    as.data.frame() %>%
    mutate(dif.PRI = estPRI - resultadoReal$PRI,
           dif.PAN = estPAN - resultadoReal$PAN)
```


#### Afijación proporcional

```{r, message = FALSE, warning=FALSE}
source("funciones/funcionSimulaEstrVar.R")
simulacionESTR.prop <- funcionSimulaEstrVar(gobernador2015, n, M, df.distritos)
```

# CALCULO DE INTERVALO DE MUESTREO ESTRATIFICADO PROPORCIONAL E INDICADORES

```{r}
simulacionESTR.prop <- simulacionESTR.prop %>%
  mutate(MinPRI = estPRI - (1.96 * sqrt(varPRI)),
         MaxPRI = estPRI + (1.96 * sqrt(varPRI)),
         MinPAN = estPAN - (1.96 * sqrt(varPAN)),
         MaxPAN = estPAN + (1.96 * sqrt(varPAN)),
         capturaPRI = resultadoReal$PRI > MinPRI
                        && resultadoReal$PRI < MaxPRI,
         capturaPAN = resultadoReal$PAN > MinPAN
                        && resultadoReal$PAN < MaxPAN,
         no.Traslape = MaxPAN < MinPRI,
         longIntPRI = MaxPRI-MinPRI,
         longIntPAN = MaxPAN-MinPAN)
captura_verdad <- data.frame()
captura_verdad <- captura_verdad %>%
  rbind(simulacionESTR.prop %>%
          select(capturaPRI, capturaPAN, no.Traslape) %>%
          summarise(PRI.capturado = 100*length(capturaPRI[capturaPRI==TRUE]) / M,
                    PAN.capturado = 100*length(capturaPAN[capturaPAN==TRUE]) / M,
                    no.Traslapado = 100*length(no.Traslape[no.Traslape==TRUE])/M))
captura_verdad
```
```{r, echo=FALSE}
Tema <- theme(plot.title = (element_text(size = 20, color = "black")),
              plot.subtitle = (element_text(size = 10, color = "black")),
              legend.position = "top",  plot.margin = margin(0.5, 1, 0.5, 1, "cm"),
              legend.key.height = unit (0.2, "cm"), legend.key.width = unit (0.2, "cm"),
              axis.text = element_text(size = 10, color = "black"),
              legend.text = element_text(size = 8, color = "black"),
              legend.title = element_text(size = 10, color = "black"),
              plot.caption = element_text(size = 10, color = "black", face="italic"),
              axis.title = element_text(size = 12, color = "black"))
```

Error: Estratificado (proporcional)


```{r}
graficaError <-function(df.simulacion, vtitulo){
  M <- length(df.simulacion[,1])
  error <- ggplot(data=df.simulacion, aes(x=dif.PRI^2)) +
    geom_histogram(bins=50, color="red", fill = "red", alpha=0.5)+
    scale_y_continuous(labels = comma) +
    theme_bw() + Tema +
    labs(fill = "Partido", color= NULL, 
         x = "Diferencia al cuadrado", 
         y = "Observaciones", 
         title = vtitulo,
         caption = NULL, 
         subtitle = paste("Errores de", M, "simulaciones respecto al resultado observado"))
  show(error)
}
```

```{r}
titulo <- "Simulación: Muestreo estratificado (proporcional)"
graficaError(simulacionESTR.prop, titulo)
```

```{r}
graficaHistograma <-function(df.simulacion, vtitulo){
  M <- length(df.simulacion[,1])
  
  comp <- ggplot(data=df.simulacion) +
    geom_histogram(aes(x=estPRI, fill="PRI"),color="red",  alpha=0.5)+
    geom_histogram(aes(x=estPAN, fill="PAN"), color="blue",  alpha=0.5)+
    scale_fill_manual(breaks = c("PRI", "PAN"),
                      values=c("red", "blue")) +
    theme_bw() + Tema +
    labs(fill = "Partido", color= NULL, y = "", x = "% votación", title = vtitulo,
         caption = NULL, subtitle = paste("Resultados de",M, "simulaciones"))
  show(comp)
}
```

```{r}
simulacionESTR.prop %>%
  graficaHistograma("Simulación: Muestreo estratificado proporcional")
```
