---
title: "Conteo Rápido"
author: "Equipo 1"
date: "12/8/2020"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dplyr)
library(janitor)
library(kableExtra)

rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)

source("funciones/calculaECM.R")
```

## Lectura de datos

```{r}
gobernador2015<- read_excel("data/ComputoGobernador2015_Casilla.xlsx", 
                            sheet = "POR CASILLA", skip = 1) %>%
  clean_names()

UbicacionCasillas2015 <- read_excel("data/UbicacionCasillas2015.xlsx", skip = 4) %>%
  clean_names()
```

Se agrega lista nominal a la tabla de resultados por casilla

```{r}
gobernador2015 <- UbicacionCasillas2015 %>%
  left_join(gobernador2015, ., by = c("seccion", "casilla")) %>%
  select(-c(distrito_local.y, municipio.y, domicilio)) %>%
  mutate(seccion_casilla = paste(seccion, casilla)) %>%
  rename(municipio = municipio.x,
         distrito_local = distrito_local.x)
```

## Resultados globales

```{r}
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida),
            PRD = sum(prd) / sum(votacion_total_emitida)) -> Global

# Resultado global
Global <- Global * 100
Global
```

```{r}
total.casillas <- length(gobernador2015$seccion_casilla)
N <- 370          # Número de secciones
M <- 10        # Número de repeticiones
```

## Simulación: Muestreo aleatorio simple

```{r}
# Crea una matriz vacía
simulacionMAS <- matrix(rep(0, length(Global)*M), nrow = M)
colnames(simulacionMAS) <- c("PRI", "PAN", "PRD") 

t <- proc.time() # calcula tiempo: inicio 
for(i in 1:M){
  muestra <- sample(gobernador2015$seccion_casilla, N)
  gobernador2015 %>%
  filter(seccion_casilla %in% muestra) %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida),
            PRD = sum(prd) / sum(votacion_total_emitida)) %>%
    as.numeric() -> simulacionMAS[i, ]
}
proc.time()-t  # calcula tiempo: final 

# Se convierte a data frame, se multiplica por 100 y se calcula error
simulacionMAS <- data.frame(simulacionMAS * 100) %>%
    mutate(dif.PRI = PRI - Global$PRI,
           dif.PAN = PAN - Global$PAN,
           dif.PRD = PRD - Global$PRD)
```

## Simulación: Muestreo sistematizado

```{r}
# Se calcula k, la posición de la casilla inicial se elige al azar entre 1 y k
k <- round(total.casillas/N,0)

# Crea una matriz vacía
simulacionSIST <- matrix(rep(0, length(Global)*M), nrow = M)
colnames(simulacionSIST) <- c("PRI", "PAN", "PRD") 

t <- proc.time() # calcula tiempo: inicio 
for(i in 1:M){
  # Selección de posición de casilla inicial
  casilla0 <- sample(1:k, 1)

  # Seleccion de posición del resto de casillas
  posicion <- c()
  for(j in 1: N-1) {
    posicion <- c(posicion, casilla0 + j*k)
  }
  muestra <- gobernador2015$seccion_casilla[posicion]
  gobernador2015 %>%
  filter(seccion_casilla %in% muestra) %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida),
            PRD = sum(prd) / sum(votacion_total_emitida)) %>%
    as.numeric() -> simulacionSIST[i, ]
}
proc.time()-t  # calcula tiempo: final 

# Se convierte a data frame, se multiplica por 100 y se calcula error
simulacionSIST <- data.frame(simulacionSIST * 100) %>%
    mutate(dif.PRI = PRI - Global$PRI,
           dif.PAN = PAN - Global$PAN,
           dif.PRD = PRD - Global$PRD)
```

## Simulación: Estratificado, afijación simple

```{r}
df.distritos <- gobernador2015 %>%
  group_by(distrito_local) %>%
  summarise(LN = sum(lista_nominal),
            n = n(),
            p = LN/sum(gobernador2015$lista_nominal)) %>%
  mutate(casillas.n = round(num.casillas = N * p)) %>%
  arrange(distrito_local)
```

```{r}
M <- 2
distritos <- df.distritos$distrito_local
num.distritos <- length(distritos)

casillas.xDistrito <- round(N / num.distritos)
casillas.xDistrito * num.distritos

# Crea una matriz vacía
simulacionESTR.simple <- matrix(rep(0, length(Global)*M), nrow = M)
colnames(simulacionESTR.simple) <- c("PRI", "PAN", "PRD") 

t <- proc.time() # calcula tiempo: inicio 
for(i in 1:M){
  
  # selección de una muestra
  muestra <- c() 
  for(j in 1: num.distritos){
    gobernador2015 %>%
    filter(distrito_local == distritos[j]) %>%
    select(seccion_casilla) -> df.temp
    muestra <- c(muestra, sample(df.temp$seccion_casilla, casillas.xDistrito))
  } 
  
  # Crea un data frame temporal con estimadores para cada estrato
  df.temporal <- gobernador2015 %>%
    filter(seccion_casilla %in% muestra) %>%
    group_by(distrito_local) %>% 
    summarise(PRI = sum(total_coalicion)/ sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida),
            PRD = sum(prd) / sum(votacion_total_emitida)) 

  # Agrega información de distritos; específicamente, el número de casillas
  df.temporal <- df.distritos %>%
    left_join(df.temporal) %>%
    summarise(estPRI = n %*% PRI / total.casillas,
              estPAN = n %*% PAN / total.casillas,
              estPRD = n %*% PRD / total.casillas) %>%
    as.numeric() -> simulacionESTR.simple[i, ]
}
proc.time()-t  # calcula tiempo: final 

rm(muestra, df.temporal, df.temp)

# Se convierte a data frame, se multiplica por 100 y se calcula error
simulacionESTR.simple <- data.frame(simulacionESTR.simple * 100) %>%
    mutate(dif.PRI = PRI - Global$PRI,
           dif.PAN = PAN - Global$PAN,
           dif.PRD = PRD - Global$PRD)
```

## Simulación: Estratificado, afijación proporcional


## Cálculo de error cuadrático medio

```{r}
options(scipen=999)
resumen <- data.frame()
resumen <- resumen %>%
  rbind(calculaECM(simulacionMAS)) %>%
  rbind(calculaECM(simulacionSIST)) %>%
  rbind(calculaECM(simulacionESTR.simple))

row.names(resumen) = c("MAS", "Sistemático", "Estr simple")
resumen
```

## Resumen de error de estimación

```{r}
summary(simulacionMAS[4:6])
```

```{r}
summary(simulacionSIST[4:6])
```

```{r}
summary(simulacionESTR.simple[4:6])
```










