---
title: "Ejemplos de elecciones cerradas"
author: "Equipo 1"
date: "2/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(readxl)
library(dplyr)
library(janitor)
library(kableExtra)
library(tidyverse)
library(extrafont)
library(scales)
library(showtext)
library(tint)
library(miniUI)
library(units)
library(ggfortify)
library(cowplot)
library(magrittr)
library(Cairo)
```

```{r}
rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)
source("funciones/muestra.R")
#source("funciones/funcionSimulaEstrVar-02.R")
source("funciones/lecturaDatos.R")
source("funciones/simEstratificado.R")
```

### Tamaño de muestra y número de repeticiones

```{r, echo = TRUE}
gobernador2015 <- lecturaDatos()
N <- length(gobernador2015$seccion_casilla)
n <- muestra(N)
M <- 1000
#z <- qnorm(1-0.01/2)
#z <- 1.96
z <- 2.575
```

```{r}
resumenSimulacion <- function(df, vz){
  df %>%
    mutate(MinPRI = estPRI - (vz * sqrt(varPRI)),
           MaxPRI = estPRI + (vz * sqrt(varPRI)),
           MinPAN = estPAN - (vz * sqrt(varPAN)),
           MaxPAN = estPAN + (vz * sqrt(varPAN)),
           capturaPRI = resultadoReal$PRI > MinPRI & resultadoReal$PRI < MaxPRI,
           capturaPAN = resultadoReal$PAN > MinPAN & resultadoReal$PAN < MaxPAN,
           #longIntPRI = MaxPRI-MinPRI,
           #longIntPAN = MaxPAN-MinPAN,
           sin.Traslape = MaxPAN < MinPRI# | MaxPRI < MinPAN
    )
}
resumenCaptura <- function(df){
  rbind(df %>%
          select(capturaPRI, capturaPAN, sin.Traslape) %>%
          summarise(PRI.capturado = 100*mean(capturaPRI),
                    PAN.capturado = 100*mean(capturaPAN),
                    sin.Traslape = 100*mean(sin.Traslape)))
}
```


```{r, echo = FALSE}
df.distritosTipo <- gobernador2015 %>%
  group_by(distrito_tipo) %>%
  summarise(LN = sum(lista_nominal),
            Nh = n(),           # Casillas por distrito
            p = LN/sum(gobernador2015$lista_nominal)) %>%   # Proporción
  mutate(nh = round(n * p)) %>%
  mutate(nh = if_else(nh == 1, 2, nh)) %>%
  dplyr::rename(estrato = distrito_tipo)
#df.distritosTipo
```

# Resultado real

```{r}
gobernador2015 <- lecturaDatos()
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal
resultadoReal %>%
  mutate(PRI - PAN)
```

```{r}
simDistritoTipo0 <- gobernador2015 %>%
  dplyr::rename(estrato = distrito_tipo) %>%
  simEstratificado(df.distritosTipo$estrato, 
                   df.distritosTipo$Nh, df.distritosTipo$nh)
```

```{r, message = FALSE}
simDistritoTipo <- resumenSimulacion(simDistritoTipo0, z)
simDistritoTipo %>%
  head()
resumenCaptura(simDistritoTipo)
```

# Resultado real PAN = PAN + 10%

```{r}
gobernador2015 <- lecturaDatos()
gobernador2015$pan <- gobernador2015$pan * 1.1
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal
resultadoReal %>%
  mutate(PRI - PAN)
```

```{r}
simDistritoTipo0 <- gobernador2015 %>%
  dplyr::rename(estrato = distrito_tipo) %>%
  simEstratificado(df.distritosTipo$estrato, 
                   df.distritosTipo$Nh, df.distritosTipo$nh)
```

```{r, message = FALSE}
simDistritoTipo <- resumenSimulacion(simDistritoTipo0, z)
simDistritoTipo %>%
  head()
resumenCaptura(simDistritoTipo)
```

# Resultado real PAN = PAN + 11%

```{r}
gobernador2015 <- lecturaDatos()
gobernador2015$pan <- gobernador2015$pan * 1.11
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal
resultadoReal %>%
  mutate(PRI - PAN)
```

```{r}
simDistritoTipo0 <- gobernador2015 %>%
  dplyr::rename(estrato = distrito_tipo) %>%
  simEstratificado(df.distritosTipo$estrato, 
                   df.distritosTipo$Nh, df.distritosTipo$nh)
```

```{r, message = FALSE}
simDistritoTipo <- resumenSimulacion(simDistritoTipo0, z)
simDistritoTipo %>%
  head()
resumenCaptura(simDistritoTipo)
```

# Resultado real PAN = PAN + 12%

```{r}
gobernador2015 <- lecturaDatos()
gobernador2015$pan <- gobernador2015$pan * 1.12
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal
resultadoReal %>%
  mutate(PRI - PAN)
```

```{r}
simDistritoTipo0 <- gobernador2015 %>%
  dplyr::rename(estrato = distrito_tipo) %>%
  simEstratificado(df.distritosTipo$estrato, 
                   df.distritosTipo$Nh, df.distritosTipo$nh)
```

```{r, message = FALSE}
simDistritoTipo <- resumenSimulacion(simDistritoTipo0, z)
simDistritoTipo %>%
  head()
resumenCaptura(simDistritoTipo)
```

# PAN = PAN + PRD + MORENA

```{r}
gobernador2015 <- lecturaDatos()
gobernador2015$pan <- gobernador2015$pan + gobernador2015$prd + 
  gobernador2015$morena + gobernador2015$humanista
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal
resultadoReal %>%
  mutate(PRI - PAN)
```

```{r}
df.distritosTipo <- gobernador2015 %>%
  group_by(distrito_tipo) %>%
  summarise(LN = sum(lista_nominal),
            Nh = n(),           # Casillas por distrito
            p = LN/sum(gobernador2015$lista_nominal)) %>%   # Proporción
  mutate(nh = round(n * p)) %>%
  mutate(nh = if_else(nh == 1, 2, nh)) %>%
  dplyr::rename(estrato = distrito_tipo)
#df.distritosTipo
```

```{r}
simDistritoTipo0 <- gobernador2015 %>%
  dplyr::rename(estrato = distrito_tipo) %>%
  simEstratificado(df.distritosTipo$estrato, 
                   df.distritosTipo$Nh, df.distritosTipo$nh)
```

```{r, message = FALSE}
simDistritoTipo <- resumenSimulacion(simDistritoTipo0, z)
simDistritoTipo %>%
  head()
resumenCaptura(simDistritoTipo)
```