---
title: "Conteo rapido muestra estratificada proporcional"
author: "Equipo 1"
date: "2/5/2021"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
library(readxl)
library(dplyr)
library(janitor)
library(magrittr)
library(plotly)
```

```{r}
rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)
source("funciones/muestra.R")
source("funciones/resultadoMuestraFija.R")
```

### Lectura de datos

```{r}
source("funciones/lecturaDatos.R")
gobernador2015 <- lecturaDatos() 
```

### Resultado real

```{r}
gobernador2015 %>%
  summarise(PRI = sum(total_coalicion) / sum(votacion_total_emitida),
            PAN = sum(pan) / sum(votacion_total_emitida)) %>%
  select(PRI, PAN) -> resultadoReal

resultadoReal
```

### Tamaño de muestra

```{r}
N <- length(gobernador2015$seccion_casilla)
n <- muestra(N)                             
z <- 2.575
#z <- qnorm(1-0.01/2)
#z <- 1.96
```

### Resumen por distrito

```{r}
df.distritosTipo <- gobernador2015 %>%
  group_by(distrito_tipo) %>%
  summarise(LN = sum(lista_nominal),
            Nh = n(),           
            p = LN/sum(gobernador2015$lista_nominal)) %>%  
  mutate(nh = round(n * p)) %>%
  mutate(nh = if_else(nh == 1, 2, nh)) %>%
  arrange(distrito_tipo) %>%
  rename(estrato = distrito_tipo)

df <- gobernador2015 %>%
    rename(estrato = distrito_tipo) 
```

### Función hora aleatoria (uniforme)

```{r}
rand.date = function(start.time, end.time, size){
  times <- seq(from=as.POSIXct(start.time), 
               to=as.POSIXct(end.time), by="min")  
  U <- runif(size, 1, length(times))  
  #weibull.times <- (1/vlambda) *(-log(1-U))^(1/valpha)
  date=times[U] 
  return(date)
}

# Prueba la función
hora.inicio <- "2021-06-06 18:00:00"
hora.final <- "2021-06-07 00:00:00"
```

### Lee muestra

```{r}
#muestra.fija <- read.csv("muestra.csv")
#write.csv(muestra.fija, "muestra_hora.csv")

muestra.fija <- read.csv("muestra_hora.csv")
#hora <- rand.date(hora.inicio, hora.final, length(muestra.fija[,1]))

muestra.fija <- muestra.fija %>%
  #cbind(hora) %>%
  #rename(casilla = x) %>%
  select(casilla, hora)
```

### Simula en el día

```{r, warning=FALSE}
cortes <- c("2021-06-06 19:00:00", "2021-06-06 19:30:00",
            "2021-06-06 20:00:00", "2021-06-06 20:30:00", 
            "2021-06-06 21:00:00", "2021-06-06 21:30:00", 
            "2021-06-06 22:00:00", "2021-06-06 22:30:00", 
            "2021-06-06 23:00:00", "2021-06-06 23:30:00", 
            "2021-06-07 00:00:00")

#casillas.capt <- c()
resumen <- data.frame()
```

```{r}
k <- length(cortes)
```

```{r, warning=FALSE}
for(i in 1:k){
  df.muestra0 <- muestra.fija %>%
    filter(hora <= cortes[i]) %>%
    select(casilla)
  muestra0 <- df.muestra0$casilla
  
  df0 <- df %>%
    filter(seccion_casilla %in% muestra0) 
  
  casillas.capt = length(muestra0)
  
  temp <- cbind(hora = cortes[i],
                resultadoMuestraFija(df0, df.distritosTipo, muestra0),
                avance= casillas.capt/length(muestra.fija$casilla))
  
  resumen <- rbind(resumen, temp)
  rm(temp)
}
#resumen
```

```{r}
print(paste("Hora de corte: ", resumen$hora[k]))
```

```{r}
votos.partido <- resumen %>%
  filter(hora == cortes[k]) %>%
  select(estPRI, estPAN, estPRD, estPT, estMORENA, 
         estHUMANISTA, estPES, estnoREG, estNULOS) %>%
  t() %>%
  as.data.frame() %>%
  rename(p = V1) %>%
  arrange() 

data <- data.frame(partido = row.names(votos.partido), p = votos.partido$p)

fig <- plot_ly(data, x = ~partido, y = ~p, type = "bar")
fig <- fig %>%
  layout(title = paste("Hora de corte:", cortes[k],
      "\nCasillas :", length(muestra0),
      "\nAvance: ", round(100 * length(muestra0)/sum(df.distritosTipo$nh), 2), "%") %>% print())
fig
```


```{r}
library(ggplot2)
data <- data.frame(
  partido = c("Coalición", "Humanista", "Morena", "PAN", 
              "Encuentro Social", "PRD", "PT"),
  porcentaje = c(resumen$estPRI[k], resumen$estHUMANISTA[k], 
                 resumen$estMORENA[k], resumen$estPAN[k],
                 resumen$estPES[k], resumen$estPRD[k], 
                 resumen$estPT[k]),
  error = c(resumen$deltaPRI[k], resumen$deltaHUMANISTA[k], 
            resumen$deltaMORENA[k], resumen$deltaPAN[k],
            resumen$deltaPES[k], resumen$deltaPRD[k], 
            resumen$deltaPT[k])
)
```


```{r}
ggplot(data) +
    geom_bar(aes(x=partido, y=porcentaje), stat="identity", fill="skyblue", alpha=0.7) +
    geom_errorbar(aes(x=partido, ymin=porcentaje-error, ymax=porcentaje+error), 
                   width=0.4, colour="orange", alpha=0.9, size=1.3)


```


### Gráfica  

```{r, warning=FALSE}
data <- resumen

fig <- plot_ly(data, 
               x = ~cortes[1:k], y = ~estPRI[1:k], type = 'scatter', name = 'PRI',
               error_y = ~list(array = deltaPRI[1:k], color = '#000000')) %>%
  add_trace(x = ~cortes[1:k], y = ~estPAN[1:k], type = 'scatter', name = 'PAN',
               error_y = ~list(array = deltaPAN[1:k], color = '#000000'))
fig
```





