---
title: "Reporte"
date: "6/6/2021"
output:
  html_document: default
  pdf_document: default
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE)
library(readxl)
library(dplyr)
library(janitor)
library(magrittr)
library(plotly)
library(ggplot2)
#library(officer)
#library(rvg)
```

```{r}
#rm(list = ls())
`%notin%` = function(x,y) !(x %in% y)
source("funciones/muestra.R")
source("funciones/resultadoMuestraFija.R")
```

```{r}
### Lectura de datos
source("funciones/lecturaDatos.R")
gobernador2015 <- lecturaDatos() 
```

```{r, warning=FALSE}
cortes <- c("2021-06-06 19:00:00", "2021-06-06 19:30:00",
            "2021-06-06 20:00:00", "2021-06-06 20:30:00", 
            "2021-06-06 21:00:00", "2021-06-06 21:30:00", 
            "2021-06-06 22:00:00", "2021-06-06 22:30:00", 
            "2021-06-06 23:00:00", "2021-06-06 23:30:00", 
            "2021-06-07 00:00:00")
#k <- 4
k  <- length(cortes)
```

```{r}
### Tamaño de muestra
N <- length(gobernador2015$seccion_casilla)
n <- muestra(N)                             
z <- 2.575
#z <- qnorm(1-0.01/2)
#z <- 1.96
```

```{r}
### Resumen por distrito
df.distritosTipo <- gobernador2015 %>%
  group_by(distrito_tipo) %>%
  summarise(LN = sum(lista_nominal),
            Nh = n(),           
            p = LN/sum(gobernador2015$lista_nominal)) %>%  
  mutate(nh = round(n * p)) %>%
  mutate(nh = if_else(nh == 1, 2, nh)) %>%
  arrange(distrito_tipo) %>%
  dplyr::rename(estrato = distrito_tipo)

df <- gobernador2015 %>%
    dplyr::rename(estrato = distrito_tipo) 
```

```{r}
### Lee muestra
#muestra.fija <- read.csv("data/muestra.csv")
#write.csv(muestra.fija, "data/muestra_hora.csv")

muestra.fija <- read.csv("data/muestra_hora.csv")
#hora <- rand.date(hora.inicio, hora.final, length(muestra.fija[,1]))
muestra.fija <- muestra.fija %>%
  #cbind(hora) %>%
  #rename(casilla = x) %>%
  select(casilla, hora)
```

```{r, warning=FALSE}
resumen <- data.frame()
for(i in 1:k){
  df.muestra0 <- muestra.fija %>%
    filter(hora <= cortes[i]) %>%
    select(casilla)
  muestra0 <- df.muestra0$casilla
  
  df0 <- df %>%
    filter(seccion_casilla %in% muestra0) 
  
  casillas.capt = length(muestra0)
  
  temp <- cbind(hora = cortes[i],
                resultadoMuestraFija(df0, df.distritosTipo, muestra0),
                avance= casillas.capt/length(muestra.fija$casilla))
  
  resumen <- rbind(resumen, temp)
  rm(temp)
}
#resumen
```

### Hora de corte: 

```{r}
resumen$hora[k]
```

### Porcentaje de avance

```{r}
paste("Se han capturado ", length(df0$seccion), " de ", n, " casillas (", 
      round(resumen$avance[k]*100,2), "%)", sep = "")
```

```{r, eval = FALSE}
df0 %>%
  select(casilla_tipo) %>%
  table()
```

```{r}
votos.partido <- resumen %>%
  filter(hora == cortes[k]) %>%
  select(estPRI, estPAN, estPRD, estPT, estMORENA, 
         estHUMANISTA, estPES, estnoREG, estNULOS) %>%
  t() %>%
  as.data.frame() %>%
  dplyr::rename(p = V1) %>%
  arrange() 

data <- data.frame(partido = row.names(votos.partido), p = votos.partido$p)
```

```{r}
data <- data.frame(
  partido = c("Coalición", "Humanista", "Morena", "PAN", 
              "Encuentro Social", "PRD", "PT"),
  porcentaje = c(resumen$estPRI[k], resumen$estHUMANISTA[k], 
                 resumen$estMORENA[k], resumen$estPAN[k],
                 resumen$estPES[k], resumen$estPRD[k], 
                 resumen$estPT[k]),
  error = c(resumen$deltaPRI[k], resumen$deltaHUMANISTA[k], 
            resumen$deltaMORENA[k], resumen$deltaPAN[k],
            resumen$deltaPES[k], resumen$deltaPRD[k], 
            resumen$deltaPT[k])
)
data[,2:3] <- data[,2:3]*100
data$porcentaje <- round(data$porcentaje,3)
```

### Porcentaje de votos por partido

```{r}
ggplot(data) +
  geom_bar(aes(x=partido, y=porcentaje), 
             stat="identity", fill="skyblue", alpha=0.7) +
  geom_errorbar(aes(x=partido, 
                      ymin=porcentaje-error, 
                      ymax=porcentaje+error), 
                   width=0.4, colour="orange", alpha=0.9, size=1.3) +
  geom_text(aes(x=partido, y = porcentaje, label = porcentaje), 
            position = position_dodge(width = 0.9), 
            size=3, vjust=-1, hjust=0.5 ,col="black")
```

### Tendencia  

```{r, warning=FALSE}
library(reshape)
df2 <- resumen %>%
  select(hora, estPRI, estPAN) %>%
  melt() %>%
  dplyr::rename(prop = value,
                partido = variable) %>%
  mutate(partido = gsub("est", "", partido),
         prop = 100*prop)

df2 <- resumen %>%
  select(hora, deltaPRI, deltaPAN) %>%
  melt() %>%
  dplyr::rename(delta = value,
                partido = variable) %>%
  mutate(partido = gsub("delta", "", partido)) %>%
  select(delta) %>%
  cbind(df2) %>%
  mutate(delta = 100*delta)
```

```{r, warning=FALSE}
df2$prop <- round(df2$prop, 2)
ggplot(df2, aes(x=hora, y=prop,
                   group=partido, color=partido)) + 
  geom_line() +
  geom_point() +
  geom_errorbar(aes(ymin=prop-delta, ymax=prop+delta), 
                width=.2,
                 position=position_dodge(0.05))
```






